tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Office type stuff
cask "firefox"
cask "google-chrome"
cask "slack"
cask "libreoffice"
cask "microsoft-teams"

# UI testing
brew "carthage"
cask "appium"

# Programming
brew "cocoapods"
brew "erlang"
brew "rebar"
brew "go"
brew "groovy"
brew "leiningen"
brew "maven"
brew "node"
brew "pyenv"
brew "python@3.8"
brew "rbenv"
brew "scala"
brew "mysql"
cask "adoptopenjdk"
cask "adoptopenjdk11"
cask "adoptopenjdk8"
cask "jetbrains-toolbox"
cask "intellij-idea-ce"
cask "pycharm-ce"
cask "webstorm"
cask "android-studio"

# General utils
brew "gnutls"
brew "emacs"
brew "md5sha1sum"
brew "watch"
brew "wget"
